<?php

/**
 * @file
 * SMS module.
 */


 /**
 * Implements hook_permission().
 */
function sms_configuration_permission() {
  return array(
    'view SMS settings' => array(
      'title' => t('View SMS settings'),
      'description' => t('Allow users with this role to view SMS settings for adjusting messages.'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function sms_configuration_menu() {

  $items = array();

  $items['admin/config/sms/settings'] = array(
    'title' => 'SMS by MSG 91',
    'description' => 'Configuration for SMS by MSG91',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sms_configuration_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'sms_configuration.admin.inc',
  );

  $items['sms/messages'] = array(
    'title' => 'SMS Messages',
    'description' => 'Different message for different forms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sms_configuration_messages_form'),
    'access arguments' => array('view SMS settings'),
    'file' => 'sms_configuration.admin.inc',
  );


  return $items;
}


/**
 * Implements hook_block_info().
 */
function sms_configuration_block_info() {
  $blocks['smsmsg91-smssender'] = array(
    'info' => t('Send SMS using MSG91'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
   $blocks['send-mail'] = array(
    'info' => t('Send Mail'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sms_configuration_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'smsmsg91-smssender':
      $block['subject'] = t('Send SMS');
      $block['content'] = drupal_get_form('sms_configuration_sms_form');
      break;
      
      
    case 'send-mail':
      $block['subject'] = t('Send Mail');
      $block['content'] = drupal_get_form('mail_configuration_form');
      break;  
  }
  return $block;
}

/**
 * Form to Send SMS .
 */
function sms_configuration_sms_form($form, &$form_state) {

  $form = array();
  $form['mobile_number'] = array(
    '#type' => 'textfield',
    '#title' => 'Mobile Number',
    '#description' => 'Each Mobile Number is separated by comma.(,)',
    '#size' => 20,
    '#maxlength' => 150,
    '#required' => TRUE,
  );

  $form['sms_message'] = array(
    '#type' => 'textarea',
    '#title' => 'Message',
    '#size' => 256,
    '#maxlength' => 256,
    '#required' => FALSE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Send SMS Now'),
    '#submit' => array('sms_configuration_sms_form_submit'),
  );

  return $form;
}

/**
 * Form to Send Mail .
 */
function mail_configuration_form($form, &$form_state) {

  $form = array();
  $form['to_email_address'] = array(
    '#type' => 'textfield',
    '#title' => 'To email Address',
    '#description' => 'Enter email address whom the mail will go',
    '#size' => 20,
    '#maxlength' => 150,
    '#required' => TRUE,
  );
  
  $form['mail_subject'] = array(
    '#type' => 'textfield',
    '#title' => 'Subject',
    '#description' => 'Enter the subject of the mail',
    '#size' => 20,
    '#maxlength' => 150,
    '#required' => TRUE,
  );

  $form['mail_body'] = array(
    '#type' => 'textarea',
    '#title' => 'Message',
    '#size' => 256,
    '#maxlength' => 256,
    '#required' => TRUE,
  );

  $form['mail_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send Mail Now'),
    '#submit' => array('mail_configuration_form_submit'),
  );

  return $form;
}

/**
 * SMS form submit.
 */
function mail_configuration_form_submit($form, &$form_state) {

  $email_ids = $form_state['values']['to_email_address'];
  $subject = $form_state['values']['mail_subject'];
  $message = $form_state['values']['mail_body'];
  
  notify_via_mail($email_ids, $subject, $message); 
  
}

function sms_configuration_mail($key, &$message, $params) {
  switch ($key) {
    case 'notify':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    //  $message['headers'] = $params['headers'];
      $message['headers']['MIME-Version'] = '1.0';
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      break;
  }
}


function notify_via_mail($email_ids, $subject, $message) {
  $params = array(
    'subject' => t($subject),
    'body' => t($message),
    //'headers' => array(
     // 'Cc' => $cc_mail_id,
//    )
  );
  $message = drupal_mail('sms_configuration', 'notify', $email_ids, language_default(), $params, '"Jnbag" <info@jnbag.in>');
  if ($message['send'] && $message['result'] ) {
      drupal_set_message("Mail has been sent to  "  . $email_ids, 'status');
  }
}

/**
 * SMS form submit.
 */
function sms_configuration_sms_form_submit($form, &$form_state) {

  $mobile = $form_state['values']['mobile_number'];
  $sms_message = $form_state['values']['sms_message'];

  /*Send SMS using PHP*/

  // This will be set up from Settings variables.
  $auth_key = variable_get('smsmsg91_authKey');

  // Multiple mobiles numbers separated by comma.
  $mobile_number = $mobile;

  // Sender ID,While using route4 sender id should be 6 characters long.
  // To be set up in settings variables.
  $sender_id = variable_get('smsmsg91_senderID');

  // Your message to send, Add URL encoding here.
  $message = urlencode($sms_message);

  // Define route.
  $route = variable_get('smsmsg91_route');
  // Prepare you post parameters.
  // Function for sending message.
  sms_configuration_send_message($mobile_number, $message, $sender_id, $route);

  // To be decided $form_state['redirect'] = '/';.
}

/**
 * Function for sending SMS.
 */
function sms_configuration_send_message($mobile_number, $message, $sender_id, $route) {

  if (empty($mobile_number)) {
    watchdog('SMSMSG91', 'Please provide mobile number for sending SMS', WATCHDOG_ERROR);
    return FALSE;
  }
  if (empty($sender_id)) {
    $sender_id = variable_get('smsmsg91_senderID');
  }
  if (empty($route)) {
    $route = variable_get('smsmsg91_route');
  }

  $auth_key = variable_get('smsmsg91_authKey', '');

  if (!empty($auth_key)) {

    $post_data = array(
      'authkey' => $auth_key,
      'mobiles' => $mobile_number,
      'message' => $message,
      'sender' => $sender_id,
      'route' => $route,
    );

    // API URL.
    $url = "https://control.msg91.com/api/sendhttp.php";

    // Init the resource.
    $ch = curl_init();
    curl_setopt_array($ch, array(
      CURLOPT_URL => $url,
      CURLOPT_RETURNTRANSFER => TRUE,
      CURLOPT_POST => TRUE,
      CURLOPT_POSTFIELDS => $post_data,
          // ,CURLOPT_FOLLOWLOCATION => true.
    ));

    // Ignore SSL certificate verification.
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

    // Get response.
    $output = curl_exec($ch);

    // Print error if any.
    if (curl_errno($ch)) {
      watchdog('SMSMSG91', 'Error while sending SMS');
      echo 'error:' . curl_error($ch);
    }

    curl_close($ch);
    drupal_set_message(t('SMS Sent'));
    watchdog('SMSMSG91', 'SMS sent to Mobile Number %mobileNumber', array('%mobileNumber' => $mobile_number));

  }
  else {
    watchdog('SMSMSG91', 'Please set authkey for MSG91 in order to send SMS', WATCHDOG_ERROR);
    return FALSE;
  }
}

/**
 * Implements hook_user_insert().
 */
function sms_configuration_user_insert(&$edit, $account, $category) {
  if (!empty($account->field_user_name)) {
    $name = $account->field_user_name['und'][0]['value'];
  }

  $username = $account->name;
  $password  = variable_get('sms_user_password', '');

  if (!empty($account->field_contact_number)) {
    $mobile_number = $account->field_contact_number['und'][0]['value'];
  }

  $message = variable_get('sms_user_register', '');
  $message = str_replace('%name', $name, $message);
  $message = str_replace('%username', $username, $message);
  $message = str_replace('%password', $password, $message);

  $sender_id = variable_get('smsmsg91_senderID');
  $route = variable_get('smsmsg91_route');

  sms_configuration_send_message($mobile_number, $message, $sender_id, $route);

}

/**
 * Implements hook_node_insert().
 */
function sms_configuration_node_insert($node) {
  global $user;
  // if ($node->type = 'upload_cash_slip' || $node->type = 'upload_cash_slip_bank' || $node->type = 'upload_cheque' || $node->type = 'upload_neft_slip') {

    $uid = $user->uid;
    $user = user_load($uid);
    if (!empty($user->field_contact_number)) {
      $user_mobile_number = $user->field_contact_number['und'][0]['value'];
    }
    $courier_mobile_number = variable_get('courier_mobile_number', '');

    if ($node->type == 'upload_cash_slip') {
      $message = variable_get('sms_upload_cash_slip', '');
    }
    elseif ($node->type == 'upload_cash_slip_bank') {
      $message = variable_get('sms_upload_cash_slip_bank', '');
    }
    elseif ($node->type == 'upload_cheque') {
      $message = variable_get('sms_upload_cheque', '');
    }
    elseif ($node->type == 'upload_neft_slip') {
      $message = variable_get('sms_upload_neft_slip', '');
    }

    if (!empty($message)) {
      if (!empty($node->field_order_id)) {
        $order_id = $node->field_order_id['und'][0]['value'];
        $message = str_replace('%order_id', $order_id, $message);
      }
    }
    $courier_message = variable_get('sms_msg_for_courier', '');
    if (!empty($courier_message)) {
      if (!empty($node->field_order_id)) {
        $order_id = $node->field_order_id['und'][0]['value'];
        $courier_message = str_replace('%order_id', $order_id, $courier_message);
      }
    }

    // send sms_message
    $sender_id = variable_get('smsmsg91_senderID');
    $route = variable_get('smsmsg91_route');

    if (!empty($message) && !empty($user_mobile_number)) {
      //sms_configuration_send_message($user_mobile_number, $message, $sender_id, $route);
    }
    if (!empty($courier_message) && !empty($courier_mobile_number)) {
      //sms_configuration_send_message($courier_mobile_number, $courier_message, $sender_id, $route);
    }
  // }
}

/**
 * Implements hook_webform_submission_insert($node, $submission)
 */
function sms_configuration_webform_submission_insert($node, $submission)  {
    if ($submission->nid == 320) {
        $message = "Thanks for submission for SR'Ship and your ID NO is " . $submission->sid . " Please wait for interview call. For more details write on srship@jnbag.in. JNBAG";
        
        $mobile_number = $submission->data[6][0];
        $sender_id = variable_get('smsmsg91_senderID');
        $route = variable_get('smsmsg91_route');

        sms_configuration_send_message($mobile_number, $message, $sender_id, $route);
    }
}

