<?php
/**
 * Implements form alter.
 */
function general_customize_form_alter(&$form, &$form_state, $form_id) {
  unset($form['account']['roles']['#options'][3]);

  if ($form_id == 'marketing_details_node_form' || $form_id == 'record_money_transfer_node_form' || $form_id == 'agent_expenses_record_node_form' || $form_id == 'bags_node_form') {
    $form['actions']['submit']['#value'] = 'Save ( सुरक्षित करे)';
    $form['actions']['preview']['#value'] = 'Preview ( एक बार देख ले)';
    $form['field_enter_expenses']['und']['add_more']['#value'] = 'Add another item ( अगला खर्च लिखे)';
    foreach ($form['field_enter_expenses']['und'] as $key => $value) {
      if (is_numeric($key)) {
        $form['field_enter_expenses']['und'][$key]['remove_button']['#value'] = 'Remove ( हटाये)';
      }

    }

  }
}

function general_customize_user_login(&$edit, $account) {
  // dpm($_SESSION);
  if (isset($_SESSION['cart_page'])) {
    unset($_SESSION['cart_page']);
    drupal_goto('cart');
  }
}


function general_customize_menu() {
  $items['verify-user'] = array(
    'title' => '',
    'page callback' => 'check_login',
    'access callback' => TRUE,
  );

  return $items;
}


function check_login() {
  $output = '<h3><a href="/user/login">With Login</a></h3><h3><a href="/cart">Without Login</a></h3>';
  $_SESSION['cart_page'] = 1;

  return $output;
}
